### ISSUE TITLE
WooSignal backend dependices

### ISSUE THREAD

**Issue by EmadBustati** [woosignal/flutter-woocommerce-app#6] opened 2020-06-22 22:08 UTC
Right now it's impossible to use Woocommerce api and Woocommerce app with any Woocommerce store without WooSignal.

What I did to make this happen:

1. Changed the ApiProvider class and changed the post method and copied/pasted some code from other dart Woocommerce api library to make my call to any http/https Woocommerce store.

2. Removed checkCart api and functionally.

3. Still trying to figure how to change shipping address api.

Is it possible to refactor some codes in the future in such a way that we could link the template to any Woocommerce backend ?

Thanks.

**Comment by agordn52** [comment] 2020-06-27 20:47
In future please forward any enhancements or features to support@woosignal.com this is not an issue with the template.

Re. your question.
The short answer is no.

It's not sustainable to manage our APIs in plugins. It sounds like you are at battle with our API. If you want to create your own that's fine but our solution works and it's not easy to implement in the ways you've suggested.

We'll continue to make our API the best it can be and provide the best features for developers/users using the app.

Closing #6 as it's not a bug.

**Closed** 2020-06-27 20:47 UTC
